#!/bin/sh

mkdir -p template/collection
mkdir -p template/download
mkdir -p template/L
mkdir -p template/R

mkdir -p $DESTDIR/usr/bin 
install -m 755 bin/* $DESTDIR/usr/bin

mkdir -p $DESTDIR/usr/share/rawmk
cp -r template $DESTDIR/usr/share/rawmk
