#!/bin/bash

# The test data (100 MB) can be downloaded here:
# http://vnd.me.cz/rawmk/rawmk-test-data.tar.gz

set -e -x
export PATH=$PWD/bin:$PATH

echo "==================================================================="
echo " TEST 1 - individual steps"
echo "==================================================================="

echo "==================================================================="
echo " prepare directory structure"
echo "==================================================================="

#prepare directory structure
rm -rf test1
cp -pr template test1

# initialize makefile
cd test1/collection

# call make - no images, do it just exits
rawmk make

echo "==================================================================="
echo " 'download' images"
echo "==================================================================="

# put files to download dir
cp ../../test_data/sbs_stereo/img_7977.cr2 \
   ../../test_data/pano/img_4971.cr2 \
   ../../test_data/pano/img_4972.cr2 \
   ../download

#put stereo files to download dir, names are different for now
cp ../../test_data/stereo/R/img_1507.cr2 ../R
cp ../../test_data/stereo/L/img_8100.cr2 ../L

echo "==================================================================="
echo " sort images"
echo "==================================================================="

#call sort
rawmk sort

#images are sorted
test -f 2012-03-24/img_7977.cr2
test -f 2014-01-28/img_4971.cr2
test -f 2014-01-28/img_4972.cr2

#stereo L R images are paired
test -f 2014-01-28/img_1507r.cr2
test -f 2014-01-28/img_1507l.cr2


cp ../../test_data/test.gpx 2014-01-28
#echo 'GEOTAG_OPTS = '"'"'-geotime<$${DateTimeOriginal}-03:00'"'" > 2014-01-28/geotag.make
echo '[ENV]
GEOTAG_OPTS=-geotime<${DateTimeOriginal}-03:00' > 2014-01-28/geotag.ini

echo "==================================================================="
echo " get default result"
echo "==================================================================="

#call make - get default results
rawmk make

#check default results
test -f 2012-03-24/img_7977.jpg
test -f 2014-01-28/img_4971.jpg
test -f 2014-01-28/img_4972.jpg

test -f 2014-01-28/img_1507.jps

# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]

echo "==================================================================="
echo " make again - nothing changed, should just check files and exit"
echo "==================================================================="

sleep 1; touch timestamp

#call make - get default results
rawmk make

test 2012-03-24/img_7977.jpg -ot timestamp
test 2014-01-28/img_4971.jpg -ot timestamp
test 2014-01-28/img_4972.jpg -ot timestamp
test 2014-01-28/img_1507.jps -ot timestamp
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]

echo "==================================================================="
echo " check 16bit processing"
echo "==================================================================="

sleep 1; touch timestamp
touch 2014-01-28/img_1507.pto
rawmk make -C 2014-01-28 OUTPUTS # no clean

test 2014-01-28/img_1507.jps -nt timestamp
test 2014-01-28/img_1507l.tif.expanded -nt timestamp
test 2014-01-28/img_1507r.tif.expanded -nt timestamp

test 2014-01-28/img_4971.jpg -ot timestamp
test 2014-01-28/img_4972.jpg -ot timestamp

rawmk make -C 2014-01-28 clean
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]



echo "==================================================================="
echo " edit rawtherapee parameters"
echo "==================================================================="

sed -i -e "s|VerticalFlip=false|VerticalFlip=true|" 2012-03-24/img_7977.cr2.pp3
sleep 1; touch timestamp
rawmk make

# this output files should be updated
test 2012-03-24/img_7977.jpg -nt timestamp

# previously created files stay unchanged
test 2014-01-28/img_4971.jpg -ot timestamp
test 2014-01-28/img_4972.jpg -ot timestamp
test 2014-01-28/img_1507.jps -ot timestamp
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]


#sbs stereo
echo "==================================================================="
echo " create stereo image from 1 SBS source"
echo "==================================================================="
rawmk add_sbs 2012-03-24/img_7977.cr2
sleep 1; touch timestamp
rawmk make

# result exists and is newly created
test -f 2012-03-24/img_7977.jps
test 2012-03-24/img_7977.jps -nt timestamp

# previously created files stay unchanged
test 2012-03-24/img_7977.jpg -ot timestamp
test 2014-01-28/img_4971.jpg -ot timestamp
test 2014-01-28/img_4972.jpg -ot timestamp
test 2014-01-28/img_1507.jps -ot timestamp
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]

#stereo from 2 images
echo "==================================================================="
echo " create stereo image from 2 independent sources"
echo "==================================================================="
rawmk add_stereo --swap 2014-01-28/img_4971.cr2 2014-01-28/img_4972.cr2
sleep 1; touch timestamp
rawmk make

# result exists and is newly created
test -f 2014-01-28/img_4972_img_4971.jps
test 2014-01-28/img_4972_img_4971.jps -nt timestamp

# previously created files stay unchanged
test 2012-03-24/img_7977.jps -ot timestamp
test 2012-03-24/img_7977.jpg -ot timestamp
test 2014-01-28/img_4971.jpg -ot timestamp
test 2014-01-28/img_4972.jpg -ot timestamp
test 2014-01-28/img_1507.jps -ot timestamp
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]


echo "==================================================================="
echo " create stereo image from 2 independent sources, swap L R images"
echo "==================================================================="
rawmk add_stereo 2014-01-28/img_4971.cr2 2014-01-28/img_4972.cr2
sleep 1; touch timestamp
rawmk make
# result exists and is newly created
test -f 2014-01-28/img_4971_img_4972.jps
test 2014-01-28/img_4971_img_4972.jps -nt timestamp

# previously created files stay unchanged
#test 2014-01-28/img_4972_img_4971.jps -ot timestamp #questuionable, this shares intermediate files
test 2012-03-24/img_7977.jps -ot timestamp
test 2012-03-24/img_7977.jpg -ot timestamp
test 2014-01-28/img_4971.jpg -ot timestamp
test 2014-01-28/img_4972.jpg -ot timestamp
test 2014-01-28/img_1507.jps -ot timestamp
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]


#pano
echo "==================================================================="
echo " create pano image - pto first"
echo "==================================================================="
rawmk add_pano --dir 2014-01-28/img_4971.cr2 2014-01-28/img_4972.cr2
sleep 1; touch timestamp
rawmk make

# result exists and is newly created, it is just pto file for now
test -f 2014-01-28/img_4971_img_4972/img_4971_img_4972.pto
test 2014-01-28/img_4971_img_4972/img_4971_img_4972.pto -nt timestamp

# previously created files stay unchanged
test 2014-01-28/img_4971_img_4972.jps -ot timestamp
test 2014-01-28/img_4972_img_4971.jps -ot timestamp 
test 2012-03-24/img_7977.jps -ot timestamp
test 2012-03-24/img_7977.jpg -ot timestamp
test 2014-01-28/img_4971.jpg -ot timestamp
test 2014-01-28/img_4972.jpg -ot timestamp
test 2014-01-28/img_1507.jps -ot timestamp
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]

echo "==================================================================="
echo " create pano image - part 2 - tiff output"
echo "==================================================================="
sleep 1; touch timestamp
rawmk make
test -f 2014-01-28/img_4971_img_4972/img_4971_img_4972.tif
test 2014-01-28/img_4971_img_4972/img_4971_img_4972.tif -nt timestamp

# previously created files stay unchanged
test 2014-01-28/img_4971_img_4972/img_4971_img_4972.pto -ot timestamp
test 2014-01-28/img_4971_img_4972.jps -ot timestamp
test 2014-01-28/img_4972_img_4971.jps -ot timestamp
test 2012-03-24/img_7977.jps -ot timestamp
test 2012-03-24/img_7977.jpg -ot timestamp
test 2014-01-28/img_4971.jpg -ot timestamp
test 2014-01-28/img_4972.jpg -ot timestamp
test 2014-01-28/img_1507.jps -ot timestamp
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]

echo "==================================================================="
echo " TEST 2 - the same as test 1, as fast as possible "
echo "==================================================================="

cd ../..
echo "==================================================================="
echo " prepare directory structure"
echo "==================================================================="

#prepare directory structure
rm -rf test2
cp -pr template test2

# initialize makefile
cd test2/collection

# call make - no images, do it just exits
rawmk make

echo "==================================================================="
echo " 'download' images"
echo "==================================================================="

# put files to download dir
cp ../../test_data/sbs_stereo/img_7977.cr2 \
   ../../test_data/pano/img_4971.cr2 \
   ../../test_data/pano/img_4972.cr2 \
   ../download

#put stereo files to download dir, names are different for now
cp ../../test_data/stereo/R/img_1507.cr2 ../R
cp ../../test_data/stereo/L/img_8100.cr2 ../L

echo "==================================================================="
echo " sort images"
echo "==================================================================="

#call sort
rawmk sort

#images are sorted
test -f 2012-03-24/img_7977.cr2
test -f 2014-01-28/img_4971.cr2
test -f 2014-01-28/img_4972.cr2

#stereo L R images are paired
test -f 2014-01-28/img_1507r.cr2
test -f 2014-01-28/img_1507l.cr2

cp ../../test_data/test.gpx 2014-01-28
#echo 'GEOTAG_OPTS = '"'"'-geotime<$${DateTimeOriginal}-03:00'"'" > 2014-01-28/geotag.make
echo '[ENV]
GEOTAG_OPTS=-geotime<${DateTimeOriginal}-03:00' > 2014-01-28/geotag.ini

echo "==================================================================="
echo " mark sbs stereo, independent stereo and pano and run make"
echo "==================================================================="

rawmk add_sbs 2012-03-24/img_7977.cr2
rawmk add_stereo --both 2014-01-28/img_4971.cr2 2014-01-28/img_4972.cr2
rawmk add_pano --dir 2014-01-28/img_4971.cr2 2014-01-28/img_4972.cr2

sleep 1; touch timestamp
rawmk make -j 8


# result exists and is newly created, it is just pto file for now
test -f 2014-01-28/img_4971_img_4972/img_4971_img_4972.pto
test -f 2014-01-28/img_4971_img_4972.jps 
test -f 2014-01-28/img_4972_img_4971.jps  
test -f 2012-03-24/img_7977.jps
test -f 2012-03-24/img_7977.jpg
test -f 2014-01-28/img_4971.jpg
test -f 2014-01-28/img_4972.jpg
test -f 2014-01-28/img_1507.jps
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]

echo "==================================================================="
echo " create pano image - part 2 - tiff output"
echo " edit rawtherapee parameters"
echo "==================================================================="

sed -i -e "s|VerticalFlip=false|VerticalFlip=true|" 2012-03-24/img_7977.cr2.pp3
rm 2012-03-24/img_7977.pto # let the file autogenerate again

sleep 1; touch timestamp
rawmk make -j 8
test -f 2014-01-28/img_4971_img_4972/img_4971_img_4972.tif
test 2014-01-28/img_4971_img_4972/img_4971_img_4972.tif -nt timestamp

test 2012-03-24/img_7977.jps -nt timestamp
test 2012-03-24/img_7977.jpg -nt timestamp

# previously created files stay unchanged
test 2014-01-28/img_4971_img_4972/img_4971_img_4972.pto -ot timestamp
test 2014-01-28/img_4971_img_4972.jps -ot timestamp
test 2014-01-28/img_4972_img_4971.jps -ot timestamp
test 2014-01-28/img_4971.jpg -ot timestamp
test 2014-01-28/img_4972.jpg -ot timestamp
test 2014-01-28/img_1507.jps -ot timestamp
# check that clean works
[ -z "`find . -name '*.expanded' -print `" ]

echo "==================================================================="
echo " all tests passed"
echo "==================================================================="
